# Generated by Django 4.2.7 on 2026-02-16 16:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_cabang', models.CharField(db_column='nama_cabang', max_length=100)),
                ('alamat', models.TextField(blank=True, db_column='alamat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'babycare.cabang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisTerapi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_terapi', models.CharField(db_column='nama_terapi', max_length=200)),
                ('harga', models.DecimalField(db_column='harga', decimal_places=2, max_digits=12)),
                ('kategori_usia_min', models.DecimalField(blank=True, db_column='kategori_usia_min', decimal_places=1, max_digits=4, null=True)),
                ('kategori_usia_max', models.DecimalField(blank=True, db_column='kategori_usia_max', decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'babycare.jenis_terapi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenis_notifikasi', models.CharField(blank=True, db_column='jenis_notifikasi', max_length=50, null=True)),
                ('pesan', models.TextField(blank=True, db_column='pesan', null=True)),
                ('tanggal_notifikasi', models.DateField(blank=True, db_column='tanggal_notifikasi', null=True)),
                ('sudah_dibaca', models.BooleanField(db_column='sudah_dibaca', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'babycare.notifikasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_pasien', models.CharField(blank=True, db_column='kode_pasien', max_length=20, null=True, unique=True)),
                ('nama_anak', models.CharField(db_column='nama_anak', max_length=150)),
                ('tanggal_lahir', models.DateField(db_column='tanggal_lahir')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], db_column='jenis_kelamin', max_length=1, null=True)),
                ('nama_orang_tua', models.CharField(blank=True, db_column='nama_orang_tua', max_length=150, null=True)),
                ('alamat', models.TextField(blank=True, db_column='alamat', null=True)),
                ('no_wa', models.CharField(blank=True, db_column='no_wa', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'babycare.pasien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, db_column='tanggal', null=True)),
                ('jumlah', models.DecimalField(db_column='jumlah', decimal_places=2, max_digits=12)),
                ('metode_pembayaran', models.CharField(blank=True, db_column='metode_pembayaran', max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, db_column='keterangan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'babycare.pemasukan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now_add=True, db_column='tanggal')),
                ('kategori', models.CharField(blank=True, db_column='kategori', max_length=100, null=True)),
                ('jumlah', models.DecimalField(db_column='jumlah', decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, db_column='keterangan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'babycare.pengeluaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(db_column='module', max_length=100)),
                ('action', models.CharField(db_column='action', max_length=50)),
                ('code', models.CharField(db_column='code', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'babycare.permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_registrasi', models.CharField(blank=True, db_column='kode_registrasi', max_length=20, null=True, unique=True)),
                ('tanggal_kunjungan', models.DateField(db_column='tanggal_kunjungan')),
                ('status', models.CharField(db_column='status', default='BOOKED', max_length=20)),
                ('harga', models.DecimalField(db_column='harga', decimal_places=2, max_digits=12)),
                ('biaya_transport', models.DecimalField(db_column='biaya_transport', decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_bayar', models.DecimalField(blank=True, db_column='total_bayar', decimal_places=2, max_digits=12, null=True)),
                ('catatan', models.TextField(blank=True, db_column='catatan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'babycare.registrasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_role', models.CharField(db_column='nama_role', max_length=50)),
                ('deskripsi', models.TextField(blank=True, db_column='deskripsi', null=True)),
            ],
            options={
                'db_table': 'babycare.roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'babycare.role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terapis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_terapis', models.CharField(db_column='nama_terapis', max_length=150)),
                ('no_hp', models.CharField(blank=True, db_column='no_hp', max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, db_column='alamat', null=True)),
                ('biaya_transport_default', models.DecimalField(db_column='biaya_transport_default', decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'babycare.terapis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportTerapis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_transport', models.DecimalField(db_column='jumlah_transport', decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(auto_now_add=True, db_column='tanggal')),
            ],
            options={
                'db_table': 'babycare.transport_terapis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'babycare.user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('cabang', models.ForeignKey(blank=True, db_column='cabang', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cabang')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'babycare.users',
                'managed': True,
            },
        ),
    ]
