# Generated by Django 4.2.7 on 2026-03-30 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrasidetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='cabang',
            field=models.ForeignKey(blank=True, db_column='cabang_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cabang'),
        ),
        migrations.AlterModelTable(
            name='cabang',
            table='cabang',
        ),
        migrations.AlterModelTable(
            name='jenisterapi',
            table='jenis_terapi',
        ),
        migrations.AlterModelTable(
            name='notifikasi',
            table='notifikasi',
        ),
        migrations.AlterModelTable(
            name='pasien',
            table='pasien',
        ),
        migrations.AlterModelTable(
            name='pemasukan',
            table='pemasukan',
        ),
        migrations.AlterModelTable(
            name='pengeluaran',
            table='pengeluaran',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='registrasi',
            table='registrasi',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permissions',
        ),
        migrations.AlterModelTable(
            name='terapis',
            table='terapis',
        ),
        migrations.AlterModelTable(
            name='transportterapis',
            table='transport_terapis',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
    ]
