# Generated by Django 4.2.7 on 2026-03-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appsettings_updated_by_alter_user_cabang_and_more'),
    ]

    operations = [
        # Create sequence for registrasi_detail.id
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE IF NOT EXISTS babycare.registrasi_detail_id_seq;
                SELECT setval('babycare.registrasi_detail_id_seq', COALESCE((SELECT MAX(id) FROM babycare.registrasi_detail), 0) + 1, false);
                ALTER TABLE babycare.registrasi_detail ALTER COLUMN id SET DEFAULT nextval('babycare.registrasi_detail_id_seq');
            """,
            reverse_sql="""
                ALTER TABLE babycare.registrasi_detail ALTER COLUMN id DROP DEFAULT;
                DROP SEQUENCE IF EXISTS babycare.registrasi_detail_id_seq;
            """
        ),
        migrations.AlterModelOptions(
            name='registrasidetail',
            options={'managed': True},
        ),
    ]
