# Generated by Django 4.2.7 on 2026-03-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_registrasi_detail_managed'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward migration: Add has_whatsapp column
            sql="""
                ALTER TABLE babycare.pasien 
                ADD COLUMN has_whatsapp BOOLEAN DEFAULT FALSE;
                
                COMMENT ON COLUMN babycare.pasien.has_whatsapp IS 'Nomor terdaftar di WhatsApp';
            """,
            # Reverse migration: Drop has_whatsapp column
            reverse_sql="""
                ALTER TABLE babycare.pasien 
                DROP COLUMN has_whatsapp;
            """
        ),
    ]
