# Generated by Django 4.2.7 on 2026-03-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_add_has_whatsapp_to_pasien'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(db_column='judul', max_length=150)),
                ('catatan', models.TextField(blank=True, db_column='catatan', null=True)),
                ('foto_sebelum', models.ImageField(blank=True, db_column='foto_sebelum', null=True, upload_to=core.models.progress_upload_path)),
                ('foto_sesudah', models.ImageField(blank=True, db_column='foto_sesudah', null=True, upload_to=core.models.progress_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='progress_created', to=settings.AUTH_USER_MODEL)),
                ('registrasi', models.ForeignKey(db_column='registrasi_id', on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.registrasi')),
            ],
            options={
                'db_table': 'progress_tracking',
                'managed': True,
                'ordering': ['-created_at'],
            },
        ),
    ]
