# Generated by Django 4.2.7 on 2026-04-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inventory_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePesan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipe_pesan', models.CharField(db_column='tipe_pesan', max_length=255)),
                ('template_pesan', models.CharField(db_column='template_pesan', max_length=255)),
            ],
            options={
                'db_table': 'template_pesan',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pemakaianbarang',
            options={'managed': True, 'ordering': ['-tanggal_pakai', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stokmasuk',
            options={'managed': True, 'ordering': ['-tanggal_masuk', '-created_at']},
        ),
    ]
