# Generated by Django 4.2.7 on 2026-04-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_templatepesan_alter_pemakaianbarang_options_and_more'),
    ]

    operations = [
        # First, change managed to True so Django will manage the table
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'managed': True},
        ),
        # Add inventory integration fields
        migrations.AddField(
            model_name='pengeluaran',
            name='barang',
            field=models.ForeignKey(
                blank=True,
                db_column='barang_id',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='pengeluaran_set',
                to='core.baranginventory',
                verbose_name='Barang Inventory'
            ),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='jumlah_barang',
            field=models.IntegerField(
                blank=True,
                db_column='jumlah_barang',
                null=True,
                verbose_name='Jumlah Barang'
            ),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='harga_satuan_beli',
            field=models.DecimalField(
                blank=True,
                db_column='harga_satuan_beli',
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name='Harga Beli/Satuan'
            ),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='supplier',
            field=models.CharField(
                blank=True,
                db_column='supplier',
                max_length=200,
                null=True,
                verbose_name='Supplier'
            ),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='no_faktur',
            field=models.CharField(
                blank=True,
                db_column='no_faktur',
                max_length=100,
                null=True,
                verbose_name='No. Faktur'
            ),
        ),
    ]
