# Generated by Django 4.2.7 on 2026-04-11 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pengeluaran_inventory_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_column='status', default='PENDING', max_length=20)),
                ('progress', models.IntegerField(db_column='progress', default=0, help_text='Progress percentage 0-100')),
                ('file_size', models.BigIntegerField(blank=True, db_column='file_size', help_text='Size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, db_column='error_message', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_column='started_at')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_log',
                'ordering': ['-started_at'],
                'managed': True,
            },
        ),
    ]
