# Generated by Django 4.2.7 on 2026-04-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_backup_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('blue', 'Blue Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme'), ('orange', 'Orange Theme')], default='light', help_text='Color theme aplikasi', max_length=20),
        ),
    ]
